### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by loothood** [lau1944/shark#10]
**Describe the bug**
After running the example, I got a white screen with a text "Something went wrong" 
<img width="351" alt="Screen Shot 2021-08-03 at 14 53 16" src="https://user-images.githubusercontent.com/11191867/127996363-2a6dfff8-4323-4ffe-85e8-751043628535.png">
on the emulator and the error in the console:
```
Running Xcode build...
Xcode build done.                                           33.3s
Debug service listening on ws://127.0.0.1:50043/-JwhQeTIzm0=/ws
Syncing files to device iPhone 12 Pro Max...
flutter: SharkError: Network error while fetching widget
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: SharkError: Error Occur while fetching UI components: DioError [DioErrorType.other]: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 50046
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
<asynchronous suspension>

#0      onError.<anonymous closure> (package:shark/src/core/share_error.dart:8:7)
#1      SharkReport.report.<anonymous closure>.<anonymous closure> (package:shark/src/core/share_error.dart:34:10)
#2      List.forEach (dart:core-patch/growable_array.dart:403:8)
#3      SharkReport.report.<anonymous closure> (package:shark/src/core/share_error.dart:33:21)
#4      new Future.microtask.<anonymous closure> (dart:async/future.dart:198:37)
#5      _rootRun (dart:async/zone.dart:1346:47)
#<…>
flutter: null
Application finished.
```

**To Reproduce**
1. Clone the repository
2. Run an example

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.1
 - flutter 2.2.3 stable
 - dart 2.13.4

**Smartphone (please complete the following information):**
 - Device: Phone12 Pro Max Simulator

**Comment by lau1944** [comment]
I saw you run on your local machine.
In order to run on local host, you need to set your emulator proxy to your host port.
For android, you can run this on your command line
`adb reverse tcp:8080 tcp:8080`

I don't know about ios emulator, you can do some google. 

Or you can use this host https://shark-sample-server.herokuapp.com

**Comment by lau1944** [comment]
I run without any problem on ios emulator.
![Simulator Screen Shot - iPhone 12 mini - 2021-08-03 at 20 13 04](https://user-images.githubusercontent.com/40358357/128013508-e0f3091a-8f8d-4dc7-9c6b-8f8bf030ef94.png)

**Comment by loothood** [comment]
> Or you can use this host https://shark-sample-server.herokuapp.com
This works for me. Thank you!
